name: tests
# Originally from: https://doc.rust-lang.org/cargo/guide/continuous-integration.html#github-actions

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --firefox --headless
